[versions] #######################################################################################
# Toolchain
kotlin = "2.4.0"
vanniktechPublish = "0.36.0"
dokka = "2.0.0"

[plugins] ########################################################################################
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
vanniktech-publish = { id = "com.vanniktech.maven.publish", version.ref = "vanniktechPublish" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
